<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>df17c5f0-c9d2-452c-912c-6d78282f9017</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\notes-out.ApiService\notes-out.ApiService.csproj" />
    <ProjectReference Include="..\notes-out.Web\notes-out.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
  </ItemGroup>

</Project>
